
# ---------------------------------------------------------------- articles ---
ARTICLES = [
 dict(slug="how-to-upgrade-ram-gaming-laptop-uk",
      title="How to Upgrade RAM in a Gaming Laptop (UK Guide)",
      meta="How to upgrade RAM in a gaming laptop: check compatibility, buy the right DDR5 SODIMM, and install it safely.",
      lead="Running out of memory? A RAM upgrade is the cheapest meaningful upgrade for a gaming laptop — often under £40. Here's how to do it safely.",
      sections=[
       ("Step 1: Check if your RAM is upgradeable","Some thin laptops (Zephyrus G14, Blade 16 on some configs) have soldered RAM that can't be upgraded. Check your model's spec sheet or our <a href='/guides/how-to-choose-gaming-laptop.html'>buying guide</a> first. Most 15-16 inch models have two SODIMM slots."),
       ("Step 2: Buy the right memory","Match the generation (DDR4 vs DDR5) and speed (e.g. DDR5-4800). For dual-channel performance, buy a matched pair — 2x8GB or 2x16GB. Reputable UK sellers: Amazon UK, Crucial UK, Box."),
       ("Step 3: Install it","Power off, unplug, and remove the bottom panel (usually 8-12 Phillips screws). Ground yourself, release the clips, slot the new sticks at 45°, press down until they click. Boot and verify in Task Manager."),
       ("How much RAM do you need?","16GB is the 2026 baseline for gaming. 32GB helps for video editing, VMs and heavy multitasking — but won't raise FPS.")],
      faqs=[("Will upgrading RAM void my warranty?","On most brands, no — RAM and SSD are considered user-upgradeable. Keep the original sticks in case of a warranty claim."),
            ("Does more RAM increase FPS?","Going from 8GB to 16GB can help; beyond 16GB there's no gaming benefit, but multitasking improves.")]),
 dict(slug="how-to-upgrade-ssd-gaming-laptop-uk",
      title="How to Upgrade SSD Storage in a Gaming Laptop",
      meta="Upgrade your gaming laptop's SSD: clone your drive, pick the right NVMe SSD, and double your storage.",
      lead="Modern games are 100GB+ each — 512GB fills fast. Adding a second NVMe SSD is easy and cheap. Here's the full process.",
      sections=[
       ("Check your slots","Most gaming laptops have two M.2 slots (one occupied). Check the manual — some budget models have only one."),
       ("Pick the right SSD","Any PCIe Gen 4 NVMe M.2 2280 SSD works. 1TB is the sweet spot (~£60-80 in the UK); 2TB if you hoard games. Samsung 990 Pro, WD Black SN850X and Crucial T705 are safe bets."),
       ("Clone or fresh install?","For a second drive: just slot it in and format in Disk Management. To replace the boot drive, clone with Macrium Reflect (free) or Samsung Magician, then swap."),
       ("Don't forget the heatsink","Gen 4 SSDs run hot — use the laptop's thermal pad or a thin graphene heatsink if there's clearance.")],
      faqs=[("Can I add a second SSD to any gaming laptop?","Most 15-16 inch models have a spare M.2 slot. Thin 14-inch models often don't — check first."),
            ("Will a faster SSD improve gaming FPS?","No, but load times shrink dramatically versus old SATA drives.")]),
 dict(slug="what-is-mux-switch-gaming-laptop",
      title="What is a MUX Switch in a Gaming Laptop? (Explained)",
      meta="MUX switch explained: what it does, how much FPS it adds, and whether you need it in 2026.",
      lead="You've seen 'MUX switch' on spec sheets. It's a small chip that can add 5-15% gaming performance — here's how it works and when it matters.",
      sections=[
       ("The problem it solves","Normally your dedicated GPU sends frames through the integrated GPU to reach the display — adding latency and costing ~5-10% performance. A MUX (multiplexer) switch lets the dGPU talk directly to the display."),
       ("How much difference does it make?","Typically 5-15% more FPS, biggest at 1080p and in CPU-bound games. At 1440p+ the gap shrinks."),
       ("NVIDIA Advanced Optimus","The automatic version — switches intelligently without a reboot. Found on most 2024+ premium laptops, including our top picks."),
       ("Do you need it?","Nice to have, not essential. Don't pick an inferior laptop just for a MUX switch — but between two equal machines, take the one that has it.")],
      faqs=[("Does MUX switch affect battery life?","Yes — direct GPU mode uses more power. Advanced Optimus solves this by switching automatically."),
            ("How do I enable the MUX switch?","In Armoury Crate (ASUS), Legion Zone (Lenovo) or the NVIDIA Control Panel — look for 'dGPU only' or 'Ultimate' mode.")]),
 dict(slug="dlss-3-frame-generation-laptops-explained",
      title="DLSS 3 & Frame Generation on Gaming Laptops — Explained",
      meta="DLSS 3 frame generation explained for laptop gamers: how it works, which GPUs support it, and real FPS gains.",
      lead="DLSS 3 is the closest thing to free performance in PC gaming — AI-generated frames that can nearly double your FPS. Here's what laptop buyers need to know.",
      sections=[
       ("How it works","DLSS combines AI upscaling (render at lower resolution, reconstruct sharp) with frame generation (AI creates entire frames between rendered ones). Result: much higher FPS with minimal quality loss."),
       ("Which laptop GPUs support it?","All RTX 40-series laptop GPUs — RTX 4050 through 4090. Older RTX 30-series gets DLSS 2 upscaling only, no frame generation."),
       ("Real-world gains","In Cyberpunk 2077 at 1440p, an RTX 4060 laptop jumps from ~45fps to ~80fps with DLSS 3 Quality + frame gen. It's transformative on mid-range GPUs."),
       ("The catch","Slightly higher input latency — use NVIDIA Reflex (usually auto-enabled) to counter it. Not ideal for competitive esports, perfect for cinematic AAA games.")],
      faqs=[("Does DLSS 3 work on all games?","No — around 300+ supported titles and growing. Check the game's graphics settings."),
            ("Is FSR 3 the same?","AMD's alternative works on any GPU including NVIDIA, but DLSS 3 quality is generally better.")]),
 dict(slug="how-to-keep-gaming-laptop-cool",
      title="How to Keep Your Gaming Laptop Cool (10 Proven Tips)",
      meta="10 proven ways to keep your gaming laptop cool: cooling pads, undervolting, repasting, fan curves and more.",
      lead="Heat is the enemy of laptop performance — hot chips throttle and get loud. These ten tips will drop temperatures by 5-15°C.",
      sections=[
       ("1. Lift the rear","The cheapest fix: a £10 laptop stand improves airflow more than you'd expect. Rear elevation matters most."),
       ("2. Use a cooling pad","Good for 3-7°C. Get one with large, quiet fans positioned under your laptop's intakes."),
       ("3. Clean the fans","Dust chokes cooling within months. Blow out vents with compressed air every 3-6 months."),
       ("4. Undervolt the CPU","Intel XTU or Throttlestop can cut 5-10°C with zero performance loss on unlocked chips."),
       ("5. Cap your FPS","Running 300fps in menus cooks your GPU for nothing. Cap at your display's refresh rate."),
       ("6. Repaste (advanced)","After 2+ years, factory thermal paste dries out. A quality repaste (Thermal Grizzly Kryonaut) can drop 8-12°C — but it may void warranty."),
       ("7. Game in a cool room","Ambient temperature directly sets your floor. Every degree of room temp is a degree of CPU temp."),
       ("8. Use manufacturer performance modes","'Turbo' isn't always best — 'Performance' or 'Balanced' often gives 95% of FPS at far lower temps and noise."),
       ("9. Limit background apps","Chrome with 40 tabs while gaming wastes CPU cycles and heat budget."),
       ("10. Elevate, don't insulate","Never game on a bed or sofa — soft surfaces block intakes completely. Always a hard, flat surface.")],
      faqs=[("What temperature is safe for a gaming laptop?","Under 90°C CPU / 85°C GPU under load is normal. Sustained 95°C+ means repaste or better cooling."),
            ("Do cooling pads actually work?","Yes — modestly. Expect 3-7°C, more on laptops with bottom intakes.")]),
 dict(slug="gaming-laptop-vs-desktop-uk-2026",
      title="Gaming Laptop vs Desktop in the UK (2026) — Which Should You Buy?",
      meta="Gaming laptop vs desktop compared for UK buyers: performance, price, upgradeability and value in 2026.",
      lead="The eternal debate. We compare on performance per pound, upgradeability, and real UK prices — no fanboyism.",
      sections=[
       ("Performance per pound","Desktops win clearly: a £1,200 desktop beats a £1,600 laptop with the 'same' GPU, because desktop chips run at much higher wattage. Expect 20-35% more frames from the desktop."),
       ("Total cost of ownership","Desktops can be upgraded piecemeal (new GPU in 3 years); laptops must be replaced whole. Over 6 years, the desktop is usually cheaper despite the higher upfront cost with monitor and peripherals."),
       ("When a laptop wins","You move between home/uni/work. You have no desk space. You need one machine for everything. Portability is the laptop's killer feature — desktops can't compete."),
       ("The UK price reality","Prebuilt desktops from UK builders (PCSpecialist, AWD-IT) narrow the DIY gap. Factor in a £200-300 monitor for the desktop side."),
       ("Our verdict","Stationary gamer? Desktop. Student, commuter, or small flat? A laptop like the <a href='/reviews/lenovo-legion-pro-5.html'>Legion Pro 5</a> is the smart buy.")],
      faqs=[("Is a £1500 gaming laptop as good as a £1500 desktop?","No — the desktop will be ~25% faster. You're paying for portability."),
            ("Do gaming laptops last as long as desktops?","Typically 3-5 years vs 5-8 for desktops, due to heat and non-upgradeable GPUs.")]),
 dict(slug="how-long-do-gaming-laptops-last",
      title="How Long Do Gaming Laptops Last? (Realistic Lifespan Guide)",
      meta="How long do gaming laptops last? Realistic lifespan by tier, what fails first, and how to make yours last longer.",
      lead="A gaming laptop is a big investment — here's how many years you can realistically expect, and how to stretch it.",
      sections=[
       ("Realistic lifespans","Budget (RTX 4050): 3-4 years of good 1080p gaming. Mid-range (RTX 4060/4070): 4-5 years. Flagship (RTX 4080): 5-6 years before it feels slow."),
       ("What fails first?","1) Battery (2-3 years of heavy use). 2) Thermal paste drying (2-3 years). 3) Fans wearing out. 4) The GPU becoming obsolete — the one thing you can't fix."),
       ("How to extend its life","Keep it cool and clean, repaste at year 2-3, replace the battery when capacity drops under 70%, upgrade RAM/SSD instead of replacing, and use DLSS to keep frame rates up as games get heavier."),
       ("When to replace vs repair","Repair if: battery, fans, SSD, RAM, screen. Replace if: the GPU can't hit 60fps in games you play even with DLSS — that's the end of the road.")],
      faqs=[("Do gaming laptops die faster than normal laptops?","Somewhat — sustained heat stresses components. Good cooling habits close most of the gap."),
            ("Is extended warranty worth it?","On £1,500+ laptops, usually yes — one motherboard repair exceeds the warranty cost.")]),
 dict(slug="student-discount-gaming-laptops-uk",
      title="Student Discount on Gaming Laptops UK — How to Save 10%+ (2026)",
      meta="Student discount on gaming laptops in the UK: UNiDAYS, education stores and timing tricks to save hundreds.",
      lead="Students can stack serious savings on gaming laptops. Here's every legitimate discount route in the UK.",
      sections=[
       ("UNiDAYS & Student Beans","Verify your student status for 5-10% off at HP, Lenovo, Dell and Currys. Lenovo's education store is often the cheapest route to a Legion."),
       ("Manufacturer education stores","Apple-style education pricing exists for Lenovo, HP and Dell — sometimes beating sale prices on current models."),
       ("Stack with sales","Student discount + Black Friday/Prime Day = the lowest prices of the year. Time big purchases for late November."),
       ("Refurbished + student discount","Some outlets let you combine — always worth asking support."),
       ("What you'll need","A university email or UNiDAYS verification. Most stores accept any UK higher-education enrolment.")],
      faqs=[("Can I use student discount on sale items?","Usually yes with education stores; UNiDAYS codes sometimes exclude already-discounted items."),
            ("Do I need to be a university student?","Most schemes accept any UK higher/further education student with verification.")]),
 dict(slug="best-time-to-buy-gaming-laptop-uk",
      title="Best Time to Buy a Gaming Laptop in the UK (2026 Calendar)",
      meta="When to buy a gaming laptop in the UK: Black Friday, Prime Day, Boxing Day and new-GPU launch windows ranked.",
      lead="Timing your purchase can save £200-500. Here's the UK sale calendar ranked by discount depth.",
      sections=[
       ("1. Black Friday (late November)","The deepest discounts — £200-500 off premium models. Start watching prices 2 weeks early."),
       ("2. Amazon Prime Day (July + October)","Strong on ASUS, Acer and Lenovo models. The October event is now a genuine second Prime Day."),
       ("3. Boxing Day / January sales","Retailers clear stock — great for last-gen models at 20-30% off."),
       ("4. New GPU launches","When new GPUs launch, previous-gen laptops drop 15-25%. Buy last-gen for the best value."),
       ("5. Back to school (August-September)","Student-focused deals and bundles — good for sub-£1,000 machines."),
       ("Worst times to buy","Right after launch (full RRP) and mid-summer when stock is thin.")],
      faqs=[("Should I wait for Black Friday?","If it's more than 6 weeks away and you can wait, usually yes — savings average £200+."),
            ("Do prices drop on Prime Day?","Yes — particularly ASUS and Acer models on Amazon UK.")]),
 dict(slug="egpu-vs-gaming-laptop-uk",
      title="eGPU vs Gaming Laptop in the UK — Which Makes Sense in 2026?",
      meta="eGPU vs gaming laptop compared: cost, performance loss, and who should buy an external GPU enclosure.",
      lead="Already own a thin laptop? An external GPU enclosure could add gaming power — but the maths rarely works in 2026. Here's why.",
      sections=[
       ("The cost problem","A decent enclosure (£250-350) + GPU (£400-600) = £650-950 — the price of a full RTX 4050/4060 gaming laptop with screen, keyboard and portability included."),
       ("The performance penalty","Thunderbolt 3/4 bottlenecks cost 10-25% of the GPU's performance versus the same card in a desktop."),
       ("When eGPU makes sense","You already own a powerful thin-and-light (e.g. a MacBook or ultrabook for work) and only game docked at a desk. One machine, two roles."),
       ("The better alternative","For most people, selling the old laptop and buying a proper gaming laptop (like our <a href='/guides/best-gaming-laptops-under-1000-uk.html'>sub-£1,000 picks</a>) gives more performance for similar money.")],
      faqs=[("Does eGPU work with any laptop?","You need Thunderbolt 3/4 or USB4 with PCIe support — check your specs. Many budget laptops lack it."),
            ("Is eGPU worth it in 2026?","Rarely for new buyers. It only makes sense if you already own a compatible premium ultrabook.")]),
 dict(slug="what-is-nvidia-advanced-optimus",
      title="NVIDIA Advanced Optimus Explained — Do You Need It?",
      meta="NVIDIA Advanced Optimus explained: automatic GPU switching, battery life and gaming performance benefits.",
      lead="Advanced Optimus is NVIDIA's automatic MUX switch — all the performance benefit, none of the reboots. Here's how it works.",
      sections=[
       ("What it does","Automatically routes the display to the dedicated GPU when gaming and back to integrated graphics for battery life — no reboot, no manual toggle like old MUX switches."),
       ("Requirements","RTX 30-series or newer, plus a laptop manufacturer that implemented it (most 2022+ premium models). Check the spec sheet — it's not universal."),
       ("Performance impact","Same 5-15% uplift as a manual MUX switch in dGPU mode, with integrated-graphics battery life when idle. Best of both worlds."),
       ("Do you need it?","Strongly preferred on premium laptops. On budget models it's rare — don't overpay just for it.")],
      faqs=[("How do I know if my laptop has Advanced Optimus?","Check NVIDIA Control Panel > Display > 'Optimus' section, or the manufacturer's spec page."),
            ("Advanced Optimus vs MUX switch?","Advanced Optimus IS an automatic MUX switch. Manual MUX requires a reboot to switch modes.")]),
 dict(slug="gaming-laptop-battery-tips-uk",
      title="Gaming Laptop Battery Life: 9 Tips to Make It Last Longer",
      meta="Make your gaming laptop battery last longer: 9 practical tips for battery life and battery health.",
      lead="Gaming laptops aren't known for battery life — but these tips can take you from 3 hours to 6+ of real work, and keep the battery healthy for years.",
      sections=[
       ("1. Use iGPU mode","Force integrated graphics for desktop work (Advanced Optimus does this automatically). This alone can double battery life."),
       ("2. Lower refresh rate on battery","Drop from 240Hz to 60Hz when unplugged — the display is a huge power draw."),
       ("3. Cap battery charge at 80%","Most manufacturers offer a battery health mode. Keeping lithium at 80% dramatically extends lifespan if you're usually plugged in."),
       ("4. Quiet/Silent power plan","Manufacturer silent modes cut CPU wattage massively for browsing and documents."),
       ("5. Reduce brightness","The screen is the #1 drain. 50% brightness is plenty indoors."),
       ("6. Kill background apps","Discord, Chrome and launchers all sip power constantly."),
       ("7. Disable keyboard RGB on battery","Pretty, but thirsty."),
       ("8. Undervolt if supported","Less heat = less fan = less power."),
       ("9. Replace when degraded","A £60-100 replacement battery at year 3 beats buying a new laptop.")],
      faqs=[("Why does my gaming laptop only last 2 hours?","The dGPU is probably active. Switch to iGPU mode and check what's draining power in Task Manager."),
            ("Is it bad to leave it plugged in?","Modern laptops manage this well, especially with an 80% charge cap enabled.")]),
]
